### PR TITLE
Add missing quote in QueryResults documentation

### PR DESCRIPTION
**Pull request by msssk**

### CODE REVIEW

**Comment by neonstalwart** [comment]
oh... i thought this repo was still readonly.

**Comment by uhop** [comment]
It is. And it broke the mirror. So I had rollback that innocent change. Please use normal channels: trac, svn, forum, to submit bug reports and their fixes until it is announced to do differently.

**Comment by uhop** [comment]
BTW, I can make dojo/dojox/dijit/demos/util repositories truly read-only for all but the mirroring robot. Right now it is on an honor system, which was violated twice already. Thoughts?

**Comment by neonstalwart** [comment]
i think it wouldn't hurt to make those truly read-only since that is their only true purpose right now.

**Comment by wkeese** [comment]
Yah agreed, that would keep me from checking things in by accident,
thinking they are part of the dojo/docs repository (unfortunately it won't
stop people from getting confused and posting patches to github instead of
bugs.dojotoolkit.org).

**Comment by neonstalwart** [comment]
it's possible to turn off the issues but I'm not sure if that stops pull requests.  regardless, if we turn issues off it will at least stop bug reports on these repos.

## 

ben...

**Pull request merged**
